#!/usr/bin/env python3
"""
Write parts.scad: the stand-in blocks the preview draws on the board.

preview.scad used to carry these as literal coordinates, and they went stale
the moment the board was re-laid-out -- the pictures then showed the OLD
placement inside the NEW case, which is worse than no picture, because it
looks like a check that passed. Nothing else in this project restates the
placement by hand and this should not either.

Only the HEIGHTS are stated here. The case deliberately has no data for them
(see the note at the top of case.scad), they change nothing about the geometry,
and they exist so the exploded view looks like the thing on the bench.

    python3 gen_preview_parts.py
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent))

import check_case as cc  # noqa: E402
import gen_pcb as p  # noqa: E402

OUT = HERE / "parts.scad"

# ref -> (height above the board, colour, what it is)
#
# Nominal. The Pico's is the tallest because it includes the headers it sits
# on, which is also why its USB socket needs its own entry below.
BODIES: dict[str, tuple[float, str, str]] = {
    "U1": (12.5, "steelblue", "Pico on headers"),
    "J1": (11.0, "dimgray", "barrel jack"),
    "U2": (11.0, "steelblue", "RS-485 module"),
    "J2": (8.0, "peru", "Micro-Fit"),
    "F1": (7.0, "gainsboro", "fuse and clips"),
}

# The Pico's USB socket, which is not on this board and so cannot come from a
# footprint outline. The numbers live in check_case.py, which is the thing
# that has to agree with them; drawn here at the height case.scad's own USB_CZ
# claims, so a window that misses the socket is visible in the picture.
USB_SHELL_W = cc.USB_SHELL_W
USB_SHELL_H = cc.USB_SHELL_H
USB_SHELL_OUT = cc.USB_SHELL_OUT


def main() -> int:
    fab = cc.boxes("F.Fab")
    n = cc.scad_numbers((HERE / "case.scad").read_text())

    lines = [
        "// GENERATED by gen_preview_parts.py -- do not edit.",
        "// Stand-in blocks for the exploded view, read from the real",
        "// placement in gen_pcb.py so they cannot drift from the board.",
        "//",
        "// [x0, y0, x1, y1, height, z above the board, colour, label]",
        "PARTS3D = [",
    ]
    for ref, (h, colour, what) in BODIES.items():
        if ref not in fab:
            print(f"  note  {ref} has no F.Fab outline, skipped")
            continue
        x0, y0, x1, y1 = fab[ref]
        lines.append(f'  [{x0:.2f}, {y0:.2f}, {x1:.2f}, {y1:.2f}, '
                     f'{h:.1f}, 0, "{colour}", "{ref} {what}"],')

    # The socket: centred on the Pico in y, overhanging the Pico's own PCB
    # end, at the height case.scad believes it to be.
    ucen = p.PLACE["U1"][1]
    zbase = n["USB_CZ"] - n["BT"] - USB_SHELL_H / 2
    sx1 = fab["U1"][0]
    sx0 = sx1 - USB_SHELL_OUT
    lines.append(
        f'  [{sx0:.2f}, {ucen - USB_SHELL_W / 2:.2f}, {sx1:.2f}, '
        f'{ucen + USB_SHELL_W / 2:.2f}, {USB_SHELL_H:.1f}, {zbase:.2f}, '
        f'"silver", "U1 USB socket"],')
    print(f"  socket sits {sx0:.2f} mm in from the board edge; the wall "
          f"below the window is clear")
    lines += ["];", ""]

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.name}: {len(BODIES)} bodies + the USB socket, "
          f"socket {zbase:.2f} mm above the board")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
