// GENERATED by gen_preview_parts.py -- do not edit.
// Stand-in blocks for the exploded view, read from the real
// placement in gen_pcb.py so they cannot drift from the board.
//
// [x0, y0, x1, y1, height, z above the board, colour, label]
PARTS3D = [
  [3.50, 2.50, 54.50, 23.50, 12.5, 0, "steelblue", "U1 Pico on headers"],
  [1.30, 40.50, 15.70, 49.50, 11.0, 0, "dimgray", "J1 barrel jack"],
  [45.00, 26.59, 59.20, 45.41, 11.0, 0, "steelblue", "U2 RS-485 module"],
  [32.42, 44.01, 42.58, 53.92, 8.0, 0, "peru", "J2 Micro-Fit"],
  [19.51, 29.82, 42.11, 36.17, 7.0, 0, "gainsboro", "F1 fuse and clips"],
  [2.30, 9.50, 3.50, 16.50, 3.0, 11.90, "silver", "U1 USB socket"],
];
